### ISSUE TITLE
Non working example.yaml configuration

### ISSUE THREAD

**Issue by bzumik1** [lanwin/esphome_samsung_ac#10]
Hi @lanwin, 

I have finally received the HW  (I am using this #4) and I have tried to put the firmware on it based on the README.md, but I am getting this error:

<img width="1025" alt="image" src="https://github.com/lanwin/esphome_samsung_ac/assets/32042186/1a25eb7d-cff9-4e40-8477-c848b1dc17ae">

Any idea how to fix it?

**Comment by bzumik1** [comment]
I had to replace the `https://github.com/lanwin/esphome_samsung_ac@main` from example.yaml with `github://lanwin/esphome_samsung_ac@main` now it seems to be working. Not sure if this is issue on my side only or if we should update the example.yaml

**Comment by bzumik1** [comment]
Based on the [documentation](https://esphome.io/components/external_components.html) it looks like there is an issue in your example.yaml file. It either needs to be specified like this

``` yaml
external_components:
  - source:
      type: git
      url: https://github.com/lanwin/esphome_samsung_ac
      ref: main
    components: [samsung_ac ]
```

or like this

``` yaml
external_components:
  - source: github://lanwin/esphome_samsung_ac@main
    components: [samsung_ac]
```

the second one looks better to me so I would correct the example.yaml to that version but it is up to you.
