### ISSUE TITLE
Non Nasa test in esphome (Home Assistant)

### ISSUE THREAD

**Issue by wifi75** [lanwin/esphome_samsung_ac#151]
External device: AJ040FCJ2EH
two internal device: AR12HSSDBWKNEU 

hi, I'm trying to configure the yaml file in home assistant with esphome, when I perform the validation the following error appears... why?

![image](https://github.com/user-attachments/assets/76b2d26b-5be9-4dff-a7da-21a402fabd5a)

**Comment by brazoayeye** [comment]
Post the yaml file

Double check the row with # use @main if you want the latest development (possibly unstable?) 
Have you tried @main ?

**Comment by wifi75** [comment]
> Post the yaml file
> 
> Double check the row with # use @main if you want the latest development (possibly unstable?) Have you tried @main ?



# This example provides a basic configuration and description based on the M5STACK components
# For further configuration you should visit the ESPHome docs https://esphome.io
# Every line starting with a # can be removed.

```
## BASIC CONFIGURATION
esphome:
  name: samsung_ac
  friendly_name: Climate

# Select chipset and board configuration - in this case M5STACK
esp32:
  board: m5stack-atom

# [Optional] - Create web interface where you can control the AC from your web browser (without Home Assistant)
web_server:
  port: 80

# Enable logging
logger:
  level: INFO
  logs:
    component: ERROR # Remove the "Your component takes to long to respond warning"

# Enable native API for communication with Home Assistant, this can be removed if you do not plan to use it with Home Assistant
api:

# Enable OTA firmware update, you will be able to upload the firmware over WiFi without connecting the device by cables
ota:

# Setup your WiFi password
wifi:
  ssid: "WiFi" # !!!CHANGE ME!!!
  password: "My WiFi Password" # !!!CHANGE ME!!!

captive_portal:

# Specify pins used by the board to comunicate with RS485 board - in this case M5STACK
uart:
  tx_pin: GPIO19   # Use GPIO26 for ATOM Tail485 
  rx_pin: GPIO22   # Use GPIO32 for ATOM Tail485
  # For older devices it could also be 2400. But you should start with 9600.
  baud_rate: 9600
  parity: EVEN

## SAMSUNG AC CONFIGURATION

# Import custom component from GitHub
external_components:
  - source: github://lanwin/esphome_samsung_ac@stable # use @main if you want the latest development (possibly unstable?)
    components: [samsung_ac]

# Configuration of AC component
samsung_ac:

  # For NonNASA devices the following option can be enabled to prevent the device from sleeping when idle. This allows
  # values like internal and external temperature to continue to be tracked when the device isn't in use.
  non_nasa_keepalive: true

  # Capabilities configure the features alle devices of your AC system have (all parts of this section are optional). 
  # All capabilities are off by default, you need to enable only those your devices have.
  # You can override or configure them also on a per devices basis (look below for that).
  capabilities: 
    vertical_swing: true
    horizontal_swing: true
    # Presets define special AC modes like Windfree and so on. 
    # The following modes are available: sleep, quiet, fast, longreach, windfree
    presets: 
      # short version
      quiet: true
      # long version - allows to locilize names
      quiet:
        name: "Makes no sound"
        enabled: true

  devices:
    # Skip everything below on the first run! Wait a minute, watch your ESPHome logs until you see the "Discovered devices:" section and you see some addresses:
    # For NASA devices it looks like this (with 4 indoor devices): 
    #   Indoor:  20.00.00, 20.00.01, 20.00.02, 20.00.03
    # For NonNASA devices it looks like this (with 2 indoor devices): 
    #   Indoor:  00, 01
    # You need this addresses for the the sections below. If you see only a "-" then you should visit the troubleshooting section in the readme. 

    # Repeat everything below for each indoor device address you see in your logs
    - address: "20.00.00" # Indoor device address 
      # Each property below is optional (climate, room_temperature etc.) - you can delete those which you dont need.
      # For the names we suggest to choose a combination of room name and the thing it controls. 

      # Configures/overrides the capabilites for this devices. 
      # Look above for all options.
      capabilities:
        horizontal_swing: false # This device have no h swing. 

      # Creates climate control in Home Assistant. A climate control combines multiple of the controls below (like temperature, mode etc.)
      climate:
        name: "Kitchen climate"

      # The controls directly below are all included in the climate control. Its adviced to only add the climate control and skip the extra controls.
      room_temperature:
        name: "Kitchen temperature"
      target_temperature:
        name: "Kitchen target temperature"
      power:
        name: "Kitchen power"
      mode:
        name: "Kitchen mode"

      # If your AC sits near or inside the ceiling, the reported room temperature is often a little bit heigher then whats 
      # measured below. This property can be used to correct that value.
      room_temperature_offset: -1.4

      # Only supported on NASA devices
      room_humidity:
        name: "Kitchen humidity"

      # Only supported on NASA based heatpumps
      water_temperature:
        name: "Warm water"
      water_target_temperature:
        name: "Hot Water Target Temperature"
      outdoor_temperature: # Should be used with outdoor device address
        name: "Outdoor temperature"

```

**Comment by brazoayeye** [comment]
Have you tried to change
`source: github://lanwin/esphome_samsung_ac@stable`
to
`source: github://lanwin/esphome_samsung_ac@main`

**Comment by wifi75** [comment]
> Have you tried to change `source: github://lanwin/esphome_samsung_ac@stable` to `source: github://lanwin/esphome_samsung_ac@main`

ok changed, but now :

![image](https://github.com/user-attachments/assets/6599a88e-2367-4d62-a946-0b83e26cb26c)

**Comment by brazoayeye** [comment]
Right, maybe also @lanwin can change the example from
`ota:`

to 

```
ota:
  platform: esphome
```

New espHome version require that.
let me know if it work with the new like

**Comment by wifi75** [comment]
> Right, maybe also @lanwin can change the example from `ota:`
> 
> to
> 
> ```
> ota:
>   platform: esphome
> ```
> 
> New espHome version require that. let me know if it work with the new like

Yess !!!
Now I can order everything from Aliexpress, and then I'll see if it works on my two air conditioners.

a question since I have two climates inside, should I use only one yaml file or one for internal units?

can you help me setup the file for two internal units?
![image](https://github.com/user-attachments/assets/a52ddd53-3704-4cbb-a81c-b54d736c5069)

**Comment by brazoayeye** [comment]
For sure I will help, if I can.
I don't have experience regarding non nasa devices but I think that the lower layer is always a RS485 so probably only one ESP will be enough. I suppose you will connect the ESP to the same network used by the compressor and the two internal units.

Regarding the hardware be sure to buy a device with auto direction detection, because manual direction is not supported by ESPHome

**Comment by wifi75** [comment]
hi, I bought these two, are they ok?
Is the configuration as it is sufficient to manage the two internal units?

https://it.aliexpress.com/item/1005003299215808.html?srcSns=sns_Copy&spreadType=socialShare&bizType=ProductDetail&social_params=21126613437&aff_fcid=386125a53f394301bf757034a47a7f77-1722249454409-03451-_mO88aeK&tt=MG&aff_fsk=_mO88aeK&aff_platform=default&sk=_mO88aeK&aff_trace_key=386125a53f394301bf757034a47a7f77-1722249454409-03451-_mO88aeK&shareId=21126613437&businessType=ProductDetail&platform=AE&terminal_id=b3b7c9ac14dc453bbaf8c23088f9b7e9&afSmartRedirect=y

https://it.aliexpress.com/item/1005005912210853.html?srcSns=sns_Copy&spreadType=socialShare&bizType=ProductDetail&social_params=21119582716&aff_fcid=2b2145cbb5f64f4bbd9145e1ed0f8cdb-1722249457480-01235-_mLhOZQA&tt=MG&aff_fsk=_mLhOZQA&aff_platform=default&sk=_mLhOZQA&aff_trace_key=2b2145cbb5f64f4bbd9145e1ed0f8cdb-1722249457480-01235-_mLhOZQA&shareId=21119582716&businessType=ProductDetail&platform=AE&terminal_id=b3b7c9ac14dc453bbaf8c23088f9b7e9&afSmartRedirect=y

**Comment by brazoayeye** [comment]
The hardware seems right. 

For first setup just remove all devices and wait to check if address are shown. You should find at least 3 devices (maybe +1 for the wifi embedded device?) , then add 3 times - - address: part. But it's easier if you post first analysis results before proceeding.

**Comment by wifi75** [comment]
Ok then, when you have connected the hardware it will publish the results.
I found out where I should get them from?
Yes, the two indoor units have built-in WiFi

**Comment by lanwin** [comment]
> Right, maybe also @lanwin can change the example from `ota:`
> 
> to
> 
> ```
> ota:
>   platform: esphome
> ```
> 
> New espHome version require that. let me know if it work with the new like

Its now changed

**Comment by wifi75** [comment]
@brazoayeye 
the device has been delivered, already configured with esphome, now deco connect it. what do I have to do then to insert the logs here? can you explain to me?

thanks

**Comment by wifi75** [comment]
hello device connected: 
here is my log:

```

INFO ESPHome 2024.8.1
INFO Reading configuration /config/esphome/samsung.yaml...
WARNING 'samsung_ac': Using the '_' (underscore) character in the hostname is discouraged as it can cause problems with some DHCP and local name services. For more information, see https://esphome.io/guides/faq.html#why-shouldn-t-i-use-underscores-in-my-device-name
INFO Starting log output from 192.168.1.124 using esphome API
INFO Successfully connected to samsung_ac @ 192.168.1.124 in 0.088s
INFO Successful handshake with samsung_ac @ 192.168.1.124 in 0.023s
[18:25:55][I][app:100]: ESPHome version 2024.8.1 compiled on Aug 31 2024, 17:36:45
[18:25:55][W][safe_mode:029]: Last reset occurred too quickly; safe mode will be invoked in 8 restarts
```

![image](https://github.com/user-attachments/assets/fc1ef937-0a91-41c2-9b91-b1940a156d93)

**Comment by wifi75** [comment]
here is my full conficuration:

```
# This example provides a basic configuration and description based on the M5STACK components
# For further configuration you should visit the ESPHome docs https://esphome.io
# Every line starting with a # can be removed.

## BASIC CONFIGURATION
esphome:
  name: samsungsoggiorno
  friendly_name: Climate

# Select chipset and board configuration - in this case M5STACK
esp32:
  board: m5stack-atom

# [Optional] - Create web interface where you can control the AC from your web browser (without Home Assistant)
web_server:
  port: 80

# Enable logging
logger:
  level: INFO
  logs:
    component: ERROR # Remove the "Your component takes to long to respond warning"

# Enable native API for communication with Home Assistant, this can be removed if you do not plan to use it with Home Assistant
api:

# Enable OTA firmware update, you will be able to upload the firmware over WiFi without connecting the device by cables
ota:
  platform: esphome

# Setup your WiFi password
wifi:
  ssid: "WiFi" # !!!CHANGE ME!!!
  password: "12345678901234567890" # !!!CHANGE ME!!!

captive_portal:

# Specify pins used by the board to comunicate with RS485 board - in this case M5STACK
uart:
  tx_pin: GPIO19   # Use GPIO26 for ATOM Tail485 
  rx_pin: GPIO22   # Use GPIO32 for ATOM Tail485
  # For older devices it could also be 2400. But you should start with 9600.
  baud_rate: 9600
  parity: EVEN

## SAMSUNG AC CONFIGURATION

# Import custom component from GitHub
external_components:
  - source: github://lanwin/esphome_samsung_ac@main # use @main if you want the latest development (possibly unstable?)
    components: [samsung_ac]

# Configuration of AC component
samsung_ac:

  # For NonNASA devices the following option can be enabled to prevent the device from sleeping when idle. This allows
  # values like internal and external temperature to continue to be tracked when the device isn't in use.
  non_nasa_keepalive: true

  # Capabilities configure the features alle devices of your AC system have (all parts of this section are optional). 
  # All capabilities are off by default, you need to enable only those your devices have.
  # You can override or configure them also on a per devices basis (look below for that).
  capabilities: 
    vertical_swing: true
    horizontal_swing: true
    # Presets define special AC modes like Windfree and so on. 
    # The following modes are available: sleep, quiet, fast, longreach, windfree
    presets: 
      # short version
      quiet: true
      # long version - allows to locilize names
      # quiet:
      #  name: "Makes no sound"
      #  enabled: true

  devices:
    # Skip everything below on the first run! Wait a minute, watch your ESPHome logs until you see the "Discovered devices:" section and you see some addresses:
    # For NASA devices it looks like this (with 4 indoor devices): 
    #   Indoor:  20.00.00, 20.00.01, 20.00.02, 20.00.03
    # For NonNASA devices it looks like this (with 2 indoor devices): 
    #   Indoor:  00, 01
    # You need this addresses for the the sections below. If you see only a "-" then you should visit the troubleshooting section in the readme. 

    # Repeat everything below for each indoor device address you see in your logs
    - address: "20.00.00" # Indoor device address 
      # Each property below is optional (climate, room_temperature etc.) - you can delete those which you dont need.
      # For the names we suggest to choose a combination of room name and the thing it controls. 

      # Configures/overrides the capabilites for this devices. 
      # Look above for all options.
      capabilities:
        horizontal_swing: false # This device have no h swing. 

      # Creates climate control in Home Assistant. A climate control combines multiple of the controls below (like temperature, mode etc.)
      climate:
        name: "Soggiorno climate"

      # The controls directly below are all included in the climate control. Its adviced to only add the climate control and skip the extra controls.
      room_temperature:
        name: "Soggiorno temperatura"
      target_temperature:
        name: "Soggiorno target temperatura"
      power:
        name: "Soggiorno power"
      mode:
        name: "Soggiorno mode"

      # If your AC sits near or inside the ceiling, the reported room temperature is often a little bit heigher then whats 
      # measured below. This property can be used to correct that value.
      room_temperature_offset: -1.4

      # Only supported on NASA devices
      #room_humidity:
      #  name: "Kitchen humidity"

      # Only supported on NASA based heatpumps
      #water_temperature:
      #  name: "Warm water"
      #water_target_temperature:
      #  name: "Hot Water Target Temperature"
      #outdoor_temperature: # Should be used with outdoor device address
      #  name: "Outdoor temperature"
```
