### ISSUE TITLE
Can't add capabilities, error code and other extra functionality

### ISSUE THREAD

**Issue by TheChristan** [lanwin/esphome_samsung_ac#173]
I have to say this is an awesome project! Only problem I have is that I can't seem to get any of the extra functionality (capabilities, error code, offset and automatic cleaning) to work. My AC does support it but if I try to change my yaml I get this error message:
```
Failed config

samsung_ac: [source /config/esphome/esphome-ac-overloop-schuur.yaml:59]
  
  [capabilities] is an invalid option for [samsung_ac]. Please check the indentation.
  capabilities: 
    vertical_swing: True
    horizontal_swing: True
    presets: 
      windfree: 
        name: Windfree
        enabled: True
```

My indentation should be right but here you can see it for yourself (if I am doing something stupid). Please keep in mind I am new to this and ESPHome and this so it could be a really dumb mistake on my part... :)

```
# Configuration of AC component
samsung_ac:

  # Capabilities configure the features alle devices of your AC system have (all parts of this section are optional). 
  # All capabilities are off by default, you need to enable only those your devices have.
  # You can override or configure them also on a per devices basis (look below for that).
  capabilities: 
    vertical_swing: true
    horizontal_swing: true
    # Presets define special AC modes like Windfree and so on. 
    # The following modes are available: sleep, quiet, fast, longreach, windfree
    presets: 
      # long version - allows to locilize names
      windfree:
        name: "Windfree"
        enabled: true

  devices:
    - address: "20.00.02" # Indoor device address 
      # Each property below is optional (climate, room_temperature etc.) - you can delete those which you dont need.
      # For the names we suggest to choose a combination of room name and the thing it controls. 

      # Creates climate control in Home Assistant. A climate control combines multiple of the controls below (like temperature, mode etc.)
      climate:
        name: "AC Overloop schuur"

      # The controls directly below are all included in the climate control. Its adviced to only add the climate control and skip the extra controls. (Yes, I want these added controls)
      room_temperature:
        name: "Overloop schuur temperature"
      target_temperature:
        name: "Overloop schuur target temperature"
      power:
        name: "Overloop schuur power"
      mode:
        name: "Overloop schuur mode"

      #Add automatic_cleaning mode for Samsung AC NASA
      #- Added the "automatic_cleaning" feature to the Samsung AC integration.
      #- This mode ensures hygienic drying of all moisture in the indoor unit after the cooling process is completed.
      # automatic_cleaning:
      #   name: "Overloop schuur automatic clean"

      # If your AC sits near or inside the ceiling, the reported room temperature is often a little bit heigher then whats 
      # measured below. This property can be used to correct that value.
      # room_temperature_offset: -1

      # Only supported on NASA devices
      room_humidity:
        name: "Overloop schuur humidity"
      
      # This sensor captures and monitors specific error codes returned by the HVAC system.
      # When an error occurs, the sensor detects the error code and updates its value accordingly.
      # Additionally, by using the blueprint available at https://github.com/omerfaruk-aran/esphome_samsung_ac_blueprint,
      # you can automatically send detailed error messages to your mobile devices based on the captured error codes.
      # error_code:
      #   name: "Error Code"
```
