### ISSUE TITLE
How to get the data heat pump (AE160JNYDGH)

### ISSUE THREAD

**Issue by Mocky158** [lanwin/esphome_samsung_ac#23]
Hello
I apologize in advance, I'm using Github for the first time for a question, so I don't know if this is the right way to write for advice.

I created esp according to see attachment. I also attached the settings I have to the file.

The problem is that I don't know how to know that something has been read or how to change it to read other data.

This is a heat pump (AE160JNYDGH)

I'm sorry if I wrote it incomprehensible, I'm using Google translator, I'm from the Czech Republic
[Tepelné čerpadlo.txt](https://github.com/lanwin/esphome_samsung_ac/files/12879743/Tepelne.cerpadlo.txt)

![Sestrojeni](https://github.com/lanwin/esphome_samsung_ac/assets/90219705/cd70b040-64b2-4ad8-82f3-abe7d4ab2f79)

![ESP web](https://github.com/lanwin/esphome_samsung_ac/assets/90219705/4030265e-9f1c-4e1c-a010-69e86c1b8c31)

**Comment by lanwin** [comment]
> I'm sorry if I wrote it incomprehensible, I'm using Google translator, I'm from the Czech Republic

Everything is fine fine.

logger:
  level: DEBUG

Just try to change your yaml file like this:

```yaml
uart:
  tx_pin: TX
  rx_pin: RX
  baud_rate: 9600
  parity: EVEN
  debug:
    direction: BOTH
    dummy_receiver: true
    after:
      timeout: 200ms
    sequence:
      - lambda: UARTDebug::log_hex(direction, bytes, ' ');
```

This should dumpy data witch is received into the log. This way you can see if there is any data.
