### ISSUE TITLE
[Non-NASA] AJ050NCJ2EG + ESP32-S2-Mini + RS485 module - behavior and issues

### ISSUE THREAD

**Issue by TCB13** [lanwin/esphome_samsung_ac#59]
Hello,

Many thanks for putting this component together. With the provided instructions I was almost able to fully control my Samsung AJ050NCJ2EG.

My circuit is an [ESP32-S2-Mini](https://www.wemos.cc/en/latest/s2/s2_mini.html) board connected to a [TTL to RS485 module](https://vi.aliexpress.com/item/1005006100154735.html?gatewayAdapt=glo2vnm) [[details](https://www.circuitstate.com/pinouts/max485-cd4069-rs-485-module-with-auto-data-direction-control-pinout-diagram-and-pin-reference/)] like this:

![ESP-AC_Samsung_bb-vert](https://github.com/lanwin/esphome_samsung_ac/assets/6315832/abdfc054-9a1d-4295-a6f5-fb2b419a3689)

I then wired the RS485 `A+` and `B-` to `F1` and `F2` respectively in the outdoor unit (red and black wires):

![unit-boards-outside](https://github.com/lanwin/esphome_samsung_ac/assets/6315832/67ebd46c-d2bb-4907-b587-44fa61716fb6)

I'm powering this using the 12V blue plug on the unit PCB and a step down to get it to 5v. So the GND is shared between the AC unit, ESP and the RS485 module.

Here's my configuration:

````yaml
esphome:
  name: ac-samsung
  platformio_options:
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"

esp32:
  board: lolin_s2_mini
  variant: ESP32S2
  framework:
    type: arduino

logger:

api:
  encryption:
    key: ""

ota:
  safe_mode: false
  password: ""

web_server:
  port: 80
  version: 2
  ota: true
  auth:
    username: "username"
    password: "password"

wifi:
  ssid: "ssid"
  password: "password"

captive_portal:

uart:
  tx_pin: 3
  rx_pin: 2
  baud_rate: 9600
  parity: EVEN

external_components:
  - source: github://lanwin/esphome_samsung_ac@main
    components: 
      - samsung_ac

samsung_ac:
  devices:
    - address: "00"
      climate:
        name: "Bedroom climate"
      room_temperature:
        name: "Bedroom temperature"
      target_temperature:
        name: "Bedroom target temperature"
      power:
        name: "Bedroom power"
      mode:
        name: "Bedroom mode"
    - address: "01"
      climate:
        name: "Living Room climate"
      room_temperature:
        name: "Living Room temperature"
      target_temperature:
        name: "Living Room target temperature"
      power:
        name: "Living Room power"
      mode:
        name: "Living Room mode"

switch:
  - platform: restart
    name: "Restart ESP"
````

It was able to discover my units:

````
[14:35:23][W][component:214]: Component samsung_ac took a long time for an operation (0.25 s).
[14:35:23][W][component:215]: Components should block for at most 20-30ms.
[14:35:23][W][samsung_ac:018]: update
[14:35:23][C][samsung_ac:039]: Configured devices: 00, 01
[14:35:23][C][samsung_ac:059]: Discovered devices:
[14:35:23][C][samsung_ac:060]:   Outdoor: c8
[14:35:23][C][samsung_ac:061]:   Indoor:  00, 01
`````

It seems to be communicating, however I can't control them and the UI shows this behavior of **things randomly jumping around**:

![GIF 25-01-2024 17-56-29](https://github.com/lanwin/esphome_samsung_ac/assets/6315832/7a038707-7dbf-44f7-a53b-c3797173a2cd)

I can see the indoor split temperatures just fine. If I turn on one split using the AC remote the "power" toggle also change state, however if I try to power it on using the web interface it usually fails or turns on the wrong indoor unit.

The log gets written very, very fast and with a LOT of data, nevertheless I believe the only errors that show up are:

```
[14:35:23][W][samsung_ac:099]: unknown command 40
[14:35:25][W][component:214]: Component samsung_ac took a long time for an operation (0.22 s).
[14:35:25][W][component:215]: Components should block for at most 20-30ms.
````

Any ideias on what might be causing this?

Thank you.

**Comment by lanwin** [comment]
Wow that looks odd. 

Can you change the esp logger like this:

```
logger:
  level: INFO
  logs:
    component: ERROR # Remove the "Your component takes to long to respond warning"
```

This should remove the blue lines. Maybe then you could paste me some of the yellow likes in here.

What does this do?
`- "-DARDUINO_USB_CDC_ON_BOOT=0"`

Regarding you question about the step down. I had my D1mini connected to one of my indoor devices and used a step down from the V1/V2 lines. In my experience it did not worked with 5V. I had to move up to 9V before it started working without issue.
